;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Tile.Type.Montain",NewTagName="Tile.Type.Mountain")
+GameplayTagRedirects=(OldTagName="Tile.State.NearToForest",NewTagName="Tile.State.AdjacentToForest")
+GameplayTagList=(Tag="Bush",DevComment="")
+GameplayTagList=(Tag="Effect.Absorption",DevComment="")
+GameplayTagList=(Tag="Effect.Attack",DevComment="")
+GameplayTagList=(Tag="Effect.DeepRoots",DevComment="")
+GameplayTagList=(Tag="Effect.Discard",DevComment="")
+GameplayTagList=(Tag="Effect.DiscardCost",DevComment="")
+GameplayTagList=(Tag="Effect.Draw",DevComment="")
+GameplayTagList=(Tag="Effect.Ephemeral",DevComment="")
+GameplayTagList=(Tag="Effect.Expand",DevComment="")
+GameplayTagList=(Tag="Effect.Extraction",DevComment="")
+GameplayTagList=(Tag="Effect.Frenzy",DevComment="")
+GameplayTagList=(Tag="Effect.Ghost",DevComment="")
+GameplayTagList=(Tag="Effect.Growth",DevComment="")
+GameplayTagList=(Tag="Effect.Mitosis",DevComment="")
+GameplayTagList=(Tag="Effect.Movement",DevComment="")
+GameplayTagList=(Tag="Effect.Pollination",DevComment="")
+GameplayTagList=(Tag="Effect.Protection",DevComment="")
+GameplayTagList=(Tag="Effect.Rejuvenation",DevComment="")
+GameplayTagList=(Tag="Effect.Replicate",DevComment="")
+GameplayTagList=(Tag="Effect.Shield",DevComment="")
+GameplayTagList=(Tag="Effect.Thorn",DevComment="")
+GameplayTagList=(Tag="Ennemi",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building.City",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building.LumberCamp",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building.Spawner",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building.Village",DevComment="")
+GameplayTagList=(Tag="Ennemi.Building.Wall",DevComment="")
+GameplayTagList=(Tag="Ennemi.Minion",DevComment="")
+GameplayTagList=(Tag="Ennemi.Minion.ArcherLumberJack",DevComment="")
+GameplayTagList=(Tag="Ennemi.Minion.LostLumberJack",DevComment="")
+GameplayTagList=(Tag="Ennemi.Minion.LumberJack",DevComment="")
+GameplayTagList=(Tag="Ennemi.Minion.Renfort",DevComment="")
+GameplayTagList=(Tag="Sapling",DevComment="")
+GameplayTagList=(Tag="Sapling.Attack",DevComment="")
+GameplayTagList=(Tag="Sapling.Mana",DevComment="")
+GameplayTagList=(Tag="Tile.State.AdjacentToForest",DevComment="")
+GameplayTagList=(Tag="Tile.State.Fogged",DevComment="")
+GameplayTagList=(Tag="Tile.State.Revealed",DevComment="")
+GameplayTagList=(Tag="Tile.Target.IsNotValid",DevComment="")
+GameplayTagList=(Tag="Tile.Target.IsValid",DevComment="")
+GameplayTagList=(Tag="Tile.Type.City",DevComment="")
+GameplayTagList=(Tag="Tile.Type.Forest",DevComment="")
+GameplayTagList=(Tag="Tile.Type.HumanRuins",DevComment="")
+GameplayTagList=(Tag="Tile.Type.Lumbercamp",DevComment="")
+GameplayTagList=(Tag="Tile.Type.Mountain",DevComment="")
+GameplayTagList=(Tag="Tile.Type.OriginForest",DevComment="")
+GameplayTagList=(Tag="Tile.Type.Plain",DevComment="")
+GameplayTagList=(Tag="Tile.Type.PowerUp",DevComment="")
+GameplayTagList=(Tag="Tile.Type.River",DevComment="")
+GameplayTagList=(Tag="Tile.Type.Village",DevComment="")

